// VIDEO TYPES
export const GET_VIDEOS = "GET_VIDEOS";
export const CLEAR_VIDEOS = "CLEAR_VIDEOS";
export const GET_VIDEOS_FAILED = "GET_VIDEOS_FAILED";

// SELECT VIDEO TYPES
export const SELECT_VIDEO = "SELECT_VIDEO";
export const SELECT_VIDEO_FAILED = "SELECT_VIDEO_FAILED";
export const REMOVE_SELECTED_VIDEO = "REMOVE_SELECTED_VIDEO";

// SEARCH TYPES
export const SET_SEARCH = "SET_SEARCH";
